"""updated user table

Revision ID: 0ad69650beb2
Revises: e363075b4cf3
Create Date: 2026-08-04 04:07:15.973224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ad69650beb2'
down_revision = 'e363075b4cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_expiry_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('email_verification_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_expiry', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('email_verification_expiry_at')

    # ### end Alembic commands ###
