"""added email verification fields

Revision ID: 3648e7857f4e
Revises: 3d70aed2317e
Create Date: 2026-07-20 18:27:50.739905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3648e7857f4e'
down_revision = '3d70aed2317e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verification_expiry')
        batch_op.drop_column('email_verification_code')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
